gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#7aa2f7"
      - bold
    inactiveBorderColor:
      - "#545c7e"
    searchingActiveBorderColor:
      - "#e0af68"
      - bold
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#283457"
    markedBaseCommitFgColor:
      - "#e0af68"
    markedBaseCommitBgColor:
      - "#283457"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
